# fly.toml app configuration file generated for nassar-app on 2025-09-23T21:15:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nassar-app'
primary_region = 'sin'

[build]
  builder = 'heroku/buildpacks:20'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1m0s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
